---
title: "Viz part 2"
author: "Yingting Zhang"
date: "2023-10-08"
output: github_document
---

```{r}
library(tidyverse)
library(patchwork)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
#set the figure width to be six everywhere and the aspect ratio to be 0.6. And this out width means that it's going to take up 90% of the width of like an html document or a word document.
```




Get the data for plotting today
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2022-01-01",
    date_max = "2023-12-31") |>
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USW00022534 = "Molokai_HI",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())

#the things in c is monitor
```

This results in a dataframe with `r nrow(weather_df)` observations on six variables.

## Same plot from last time

```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color = name)) + geom_point(alpha=0.5)+ labs(
    title = "Temperature plot",
    x = "Min daily temp (Degrees C)",
    y ="Min daily temp",
    color = "Location",
    caption = "Max vs. min daily temp in three locations; data from rnoaa"
)
  
# do the label: labs function to x,y and color
#adding message below the x: caption function
#adding title: title function
```

```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color = name)) + geom_point(alpha=0.5)+ labs(
    title = "Temperature plot",
    x = "Min daily temp (Degrees C)",
    y ="Min daily temp",
    color = "Location",
    caption = "Max vs. min daily temp in three locations; data from rnoaa"
)+
  scale_x_continuous(
    breaks = c(-15,0,15),
    labels=c("-15 C", "0", "15")
  )+
  scale_y_continuous(
    position = "right",
    trans = "sqrt"
  )

#scale:try to modify whatever the default mapping between a variable and the aesthetic that it's mapped onto sort of how those behave

#breaks: where you want to break as exist

#position: move to the place you want (right/left)

#trans function: transfer the numbers to what types of format, like sqrt

#limit function: limit the range you want or you can filter the range by using filter to limit the range value of variables
#like:   filter(tmax >=20, tmax <=30)
```


what about colors...



```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color = name)) + geom_point(alpha=0.5)+ labs(
    title = "Temperature plot",
    x = "Min daily temp (Degrees C)",
    y ="Min daily temp",
    color = "Location",
    caption = "Max vs. min daily temp in three") + 
  viridis::scale_color_viridis(discrete = TRUE)
 # use viridis color package 
```


what is the utility of scales?

## Themes

```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color = name)) + geom_point(alpha=0.5)+ labs(
    title = "Temperature plot",
    x = "Min daily temp (Degrees C)",
    y ="Min daily temp",
    color = "Location",
    caption = "Max vs. min daily temp in three") + 
  viridis::scale_color_viridis(discrete = TRUE)+theme_minimal()+
  theme(legend.position = "bottom")
  
  #theme function to change position
#theme_bw: make the background change to other color, notice! this need to type before theme(change the position), if this take in the end, theme(position) would fail to change

#theme_bw/classic/minimal----change different ways to show pictures
```


## data argument...


```{r}
weather_df |> 
  ggplot (aes(x = date, y = tmax, color = name))+ geom_point() + geom_smooth()

nyc_weather_df = 
  weather_df |> 
  filter(name =="CentralPark_NY")

hawaii_weather_df = 
  weather_df |> 
  filter(name =="Molokai_HI")


```


## `patchwork`

```{r}
weather_df |> 
  ggplot(aes(x = date, y = tmax, color = name))+ geom_point()+ facet_grid(.~name)
```

```{r}
ggp_temp_scatter = 
  weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color = name))+ geom_point(alpha=0.5)+
theme(legend.position = "none")

ggp_prcp_density = 
  weather_df |> 
  filter(prcp>25) |> 
  ggplot(aes(x = prcp, fill = name))+ geom_density(alpha=0.5)+
theme(legend.position = "none")

ggp_temp_scatter+ggp_prcp_density
#package patchwork can put ggplot pictures next to each other

ggp_tmax_date=
  weather_df |> 
  ggplot(aes(x= date, y=tmax, color=name))+
  geom_point()+geom_smooth(se=FALSE)+theme(legend.position = "bottom")

(ggp_temp_scatter+ggp_prcp_density)/ggp_tmax_date
```


## data manipulation

```{r}
weather_df |>
  mutate(
    name = fct_relevel(name, c("Molokai_HI", "CentralPark_NY", "Waterhole_WA"))
  ) |> 
  ggplot(aes(x = name, y= tmax))+geom_boxplot()
#control the order of factors

weather_df |> 
  mutate(
    name = fct_reorder(name, tmax)
  ) |> 
  ggplot(aes(x = name, y = tmax, fill=name))+geom_violin()

#fct_reorder function: you want to put name in order according to some other variable in your data set
#like put name in order according to tamx variable: the first factors is with the lowest average tmax, the second is the one with tne next lowest
```





## complicates FAS plot

```{r}
litters_df = 
  read_csv("data/FAS_litters.csv") |> 
  janitor::clean_names() |> 
  separate(group, into = c("dose", "day_of_tx"), sep = 3)


pups_df=
  read_csv("data/FAS_pups.csv") |> 
  janitor::clean_names()

fas_df=
  left_join(pups_df, litters_df, by = "litter_number")
fas_df
#what is mean of left_join?????



fas_df |> 
  select(sex, dose, day_of_tx, starts_with("pd")) |> 
  pivot_longer(
    pd_ears:pd_walk,
    names_to = "outcome",
    values_to = "pn_day"
  ) |> 
  drop_na() |> 
  mutate(outcome = fct_reorder(outcome, pn_day)) |> 
  ggplot(aes(x = dose, y = pn_day))+ geom_violin()+
  facet_grid(day_of_tx~ outcome)
```

